### ISSUE TITLE
test for cdr-assoc is wrong, because it assumes it matches strings

### ISSUE THREAD

**Issue by Yehouda** [Symbolics/alexandria-plus#1]
https://github.com/Symbolics/alexandria-plus/blob/0617994ef39e6dc956987dd999d4c38af1110db0/tests/tests.lisp#L39

This test is wrong, because **cdr-assoc** uses **assoc** which comapre objects using **eql**, and two strings are not **eql** to each other. Using **assoc** you can pass the test to make it work, so `(assoc "foo" '(("foo" . "bar")) :test 'equalp)` does find  **("foo" . "bar")**.  The current **cdr-assoc** doesn't take the keywords like **assoc**, so just cannot do it.

https://github.com/Symbolics/alexandria-plus/blob/0617994ef39e6dc956987dd999d4c38af1110db0/lists.lisp#L30

The LispWorks **system:cdr-assoc** does take the keywords.

**Comment by Symbolics** [comment]
Commit f886514 adds the ability to pass a comparison test to `cdr-assoc` and sets the default to `equal`. The default may be set in `*assoc-test*`.
