### ISSUE TITLE
Name is confusing and ungoogleable.

### ISSUE THREAD

**Issue by slyrus** [Symbolics/alexandria-plus#2]
Is it "alexandria+" or "alexandria-plus"? Try googling it. It's a pain. Highly suggest a less user-hostile name.

**Comment by snunez1** [comment]
The problem is that Github doesn't allow `+` in a repository name, and thus the quicklisp project needs to be `-plus`.  The same issue occurs with `let+`, that has a project name of `let-plus`.

**Comment by slyrus** [comment]
Yeah, cl+ssl probably committed the original sin here. I get it. I just don't like it :). Not a huge deal but its another in a long list of (possibly unintentionally-)newbie-hostile behaviors in lisp libraries that should change, IMO. And what's the connection with alexandria? This stuff should either be in alexandria or not, not some weird extension library for it, again, IMO.
