### ISSUE TITLE
define-modify-macro requires a symbol as third argument. 

### ISSUE THREAD

**Issue by Yehouda** [Symbolics/alexandria-plus#3]
https://github.com/Symbolics/alexandria-plus/blob/b9653e54c84946e21269b804dae5d0b4886eacef/numbers.lisp#L9

This is an illegal definition, because *define-modify-macro* requires a symbol as the third argument. 
[https://www.lispworks.com/documentation/HyperSpec/Body/m_defi_2.htm#define-modify-macro](url)

You can try something like that:

```
(defmacro divf-internal (value divisor)
          (if divisor
              `(let ((e-val ,value)
                     (e-div ,divisor))
                 (if e-div
                     (/ e-val e-div)
                   (/ 1 e-val)))
            `(/ 1 ,value)))

(define-modify-macro divf (&optional divisor) divf-internal
          "Divide place by DIVISOR.  If DIVISOR is not given, divide by 1.")
```

**Comment by snunez1** [comment]
Thank you.  Fixed in [1bb9486](https://github.com/Symbolics/alexandria-plus/commit/1bb9486737a16dad758ec4509ddaa8eae902f434)
